#!/bin/bash -exu
ROOT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

source ${ROOT_DIR}/scripts/create_mod

function main(){
  cp -f $(which terraform) ${ROOT_DIR}/terraform/binary_dist
  create_mod
  pushd ${ROOT_DIR}/hsp-bbl > /dev/null
    ${ROOT_DIR}/scripts/build
  popd > /dev/null

  printf "\nBuilt binary to ${GOPATH}/bin/hsp-bbl. You will probably want to mv it to /usr/local/bin/hsp-bbl.\n"
}

main "$@"
